### ISSUE TITLE
Persian Hershey Font

### ISSUE THREAD

**Issue by mkeyno** [ldo/hersheypy#1]
hi , sorry to open ticket for my question , do you know instruction or software to convert specific fonts (Persian ) to Hershey fonts?

**Comment by ldo** [comment]
Why would you want to?

**Comment by mkeyno** [comment]
I use GRBL-plotter for my diy cnc cutter , this software is open source and easily can convert  a text to G-code , however I found that to support new font , hershey font should be installed , but according to some comment  that I've received  yet  it is not easy as it should be

**Comment by ldo** [comment]
Ah, I see. Yes, the Hershey fonts were originally designed for use on plotters.

The HersheyPy Python code includes the ability to both read Hershey fonts into its in-memory format, and write them out again. So if you have some existing stroke/plotter font in a different format, and you have code to read or generate that format, you should be able to convert between that format and the Hershey font format.

Does that help?

**Comment by mkeyno** [comment]
I'm not sure,, , honestly I was thinking to follow your advise in Inkscape , as it can convert any font to path , but I'm not sure about the code to generate format as you suggest , could you please tell me if it possible in Inkscape ? caz I only know Inkscape

**Comment by ldo** [comment]
This project is Python code. Converting font formats will require some sort of coding. Inkscape can read and write SVG files, so if you have something in that format, you can certainly manipulate it in Inkscape.

**Comment by ldo** [comment]
Nothing further to add.
